### ISSUE TITLE
docker-compose.yml

### ISSUE THREAD

**Issue by 0xF1o** [frankbaele/mindustry#2]
I had to make some changes to the example docker-compose.yml to make it work with 
 the docker/docker-compose versions that come with ubuntu 18.04.  

Maybe you want to add some of them to the example in the readme file.  

Not 100% sure about `read_only` - seems to work though.

```yml
version: '3.5' # lower version to work with current ubuntu lts
services:
  mindustry:
    image: frankbaele/mindustry
    
    # enable tty and stdin to make `docker attach` work
    tty: true
    stdin_open: true

    # trust no one :)
    read_only: true
    cap_drop:
      - ALL

    ports:
      - "6567:6567"
    restart: always

    # map config to host machine
    volumes:
      - ./config:/config

```
